FROM node:24-alpine
ENV NODE_OPTIONS="--max-old-space-size=256"
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci --prefer-offline
COPY . .
CMD ["npx", "vite", "dev", "--host", "--port", "3000"]
