apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod
resources:
  - ../../base
images:
  - name: marketrix.azurecr.io/dev/widget
    newName: marketrix.azurecr.io/prod/widget
    newTag: latest
