/**
 * Chat ID Storage Utility
 *
 * Manages chat_id storage in browser localStorage.
 * The chat_id is generated by the API and stored for persistence across page refreshes.
 */

import type { ChatMessage, InstructionType, TaskProgress } from '../types';
import {
  parseProgressLines,
  reconstructMessageContent,
  removeThinkingMarkers,
} from './messageContentUtils';
import { isBrowser } from './typeGuards';

const CHAT_ID_STORAGE_KEY = 'marketrix_chat_id';
export const CHAT_CONTEXT_STORAGE_KEY = 'marketrix_chat_context';
const PENDING_TOOL_CALL_STORAGE_KEY = 'marketrix_pending_tool_call';
const CONTEXT_VERSION = 2; // Incremented to include isOpen and isMinimized
const CONTEXT_EXPIRY_MS = 7 * 24 * 60 * 60 * 1000; // 7 days
const PENDING_TOOL_CALL_EXPIRY_MS = 5 * 60 * 1000; // 5 minutes

export interface StoredChatContext {
  version: number;
  chat_id: string;
  messages: Array<Omit<ChatMessage, 'videoStream' | 'timestamp'> & { timestamp: string }>;
  isTaskRunning: boolean;
  activeTaskId: string | null;
  taskProgress: TaskProgress[];
  currentMode: InstructionType;
  isOpen?: boolean; // Optional for backward compatibility
  isMinimized?: boolean; // Optional for backward compatibility
  timestamp: number;
}

/**
 * Get chat_id from localStorage
 */
export function getStoredChatId(): string | null {
  if (!isBrowser()) {
    return null;
  }

  try {
    const stored = localStorage.getItem(CHAT_ID_STORAGE_KEY);
    return stored || null;
  } catch (error) {
    console.warn('[Chat Storage] Failed to get chat_id from localStorage:', error);
    return null;
  }
}

/**
 * Store chat_id in localStorage
 */
export function storeChatId(chatId: string): void {
  if (!isBrowser()) {
    return;
  }

  try {
    localStorage.setItem(CHAT_ID_STORAGE_KEY, chatId);
    console.log('[Chat Storage] Stored chat_id:', chatId);
  } catch (error) {
    console.warn('[Chat Storage] Failed to store chat_id in localStorage:', error);
  }
}

/**
 * Store full chat context (messages, task state, mode, widget UI state)
 */
export function storeChatContext(
  chatId: string,
  messages: ChatMessage[],
  isTaskRunning: boolean,
  activeTaskId: string | null,
  taskProgress: TaskProgress[],
  currentMode: InstructionType,
  isOpen?: boolean,
  isMinimized?: boolean
): void {
  if (!isBrowser()) {
    return;
  }

  try {
    // Serialize messages, excluding videoStream and converting Date to ISO string
    // Also exclude placeholder messages from storage
    // IMPORTANT: System messages (like "Switched to Show mode") ARE preserved
    // Exclude "Chat context changed" messages - they're transient and will be re-added if needed
    // Remove __THINKING__ markers from content (they shouldn't be persisted)
    const serializedMessages = messages
      .filter((msg) => !msg.isPlaceholder)
      .filter((msg) => !(msg.isSystemMessage && msg.content === 'Chat context changed'))
      .map((msg) => {
        // Clean __THINKING__ markers from content before storing
        const cleanContent = removeThinkingMarkers(msg.content);
        return {
          id: msg.id,
          content: cleanContent,
          sender: msg.sender,
          timestamp: msg.timestamp.toISOString(),
          mode: msg.mode,
          isScreenAccessRequest: msg.isScreenAccessRequest,
          isSystemMessage: msg.isSystemMessage, // Preserve system messages (mode changes, etc.)
        };
      });

    // Log system messages being stored for verification
    const systemMessages = serializedMessages.filter((msg) => msg.isSystemMessage);
    if (systemMessages.length > 0) {
      console.log('[Chat Storage] Storing system messages:', {
        count: systemMessages.length,
        messages: systemMessages.map((m) => ({ id: m.id, content: m.content })),
      });
    }

    const context: StoredChatContext = {
      version: CONTEXT_VERSION,
      chat_id: chatId,
      messages: serializedMessages,
      isTaskRunning,
      activeTaskId,
      taskProgress,
      currentMode,
      isOpen,
      isMinimized,
      timestamp: Date.now(),
    };

    try {
      localStorage.setItem(CHAT_CONTEXT_STORAGE_KEY, JSON.stringify(context));
      // Only log on meaningful changes (not every state update)
      // Verification removed to reduce log noise - localStorage.setItem is reliable
    } catch (storageError: any) {
      // Handle storage quota exceeded
      if (
        storageError &&
        (storageError.name === 'QuotaExceededError' ||
          (typeof storageError === 'object' && 'code' in storageError && storageError.code === 22))
      ) {
        console.warn('[Chat Storage] Storage quota exceeded, attempting to clear old data');
        try {
          // Try to clear expired contexts and retry
          const allKeys = Object.keys(localStorage);
          const contextKeys = allKeys.filter((key) => key.startsWith('marketrix_chat_context_'));
          // Remove oldest contexts first
          const contexts = contextKeys
            .map((key) => {
              try {
                const data = localStorage.getItem(key);
                if (data) {
                  const parsed = JSON.parse(data);
                  return { key, timestamp: parsed.timestamp || 0 };
                }
              } catch {
                // Ignore corrupted entries
              }
              return null;
            })
            .filter((item): item is { key: string; timestamp: number } => item !== null)
            .sort((a, b) => a.timestamp - b.timestamp);

          // Remove oldest 50% of contexts
          const toRemove = Math.floor(contexts.length / 2);
          for (let i = 0; i < toRemove; i++) {
            localStorage.removeItem(contexts[i].key);
          }

          // Retry saving
          localStorage.setItem(CHAT_CONTEXT_STORAGE_KEY, JSON.stringify(context));
          console.log('[Chat Storage] Successfully saved after clearing old data');
        } catch (retryError) {
          console.error('[Chat Storage] Failed to save even after clearing old data:', retryError);
          throw retryError;
        }
      } else {
        throw storageError;
      }
    }
  } catch (error) {
    console.warn('[Chat Storage] Failed to store chat context:', error);
  }
}

/**
 * Get stored chat context without requiring a chat ID
 * Returns the most recent stored context regardless of chat ID
 */
export function getAnyStoredChatContext(): StoredChatContext | null {
  if (!isBrowser()) {
    return null;
  }

  try {
    const stored = localStorage.getItem(CHAT_CONTEXT_STORAGE_KEY);
    if (!stored) {
      return null;
    }

    const context: StoredChatContext = JSON.parse(stored);

    // Validate context
    if (!context || typeof context !== 'object') {
      console.warn('[Chat Storage] Invalid context format');
      return null;
    }

    // Check version compatibility (allow version 1 for backward compatibility)
    if (context.version !== CONTEXT_VERSION && context.version !== 1) {
      console.warn('[Chat Storage] Context version mismatch, ignoring stored context');
      return null;
    }

    // Check expiration (7 days)
    const age = Date.now() - context.timestamp;
    if (age > CONTEXT_EXPIRY_MS) {
      console.log('[Chat Storage] Context expired, ignoring stored context');
      clearChatContext();
      return null;
    }

    return context;
  } catch (error) {
    // Handle corrupted data gracefully
    if (error instanceof SyntaxError) {
      console.warn('[Chat Storage] Corrupted context data, clearing storage');
      try {
        localStorage.removeItem(CHAT_CONTEXT_STORAGE_KEY);
      } catch (clearError) {
        console.error('[Chat Storage] Failed to clear corrupted data:', clearError);
      }
    } else {
      console.warn('[Chat Storage] Failed to get chat context:', error);
    }
    return null;
  }
}

/**
 * Get stored chat context
 * Returns stored context even if chat ID differs (to preserve history across chat ID changes)
 */
export function getStoredChatContext(chatId: string): StoredChatContext | null {
  const context = getAnyStoredChatContext();
  if (!context) {
    return null;
  }

  // Note: We no longer require chat_id match - this allows preserving history when chat ID changes
  // The caller (restoreChatContext) will handle chat ID differences by appending a system message
  if (context.chat_id !== chatId) {
    console.log(
      '[Chat Storage] Context chat_id mismatch, but returning context to preserve history',
      {
        storedChatId: context.chat_id,
        currentChatId: chatId,
      }
    );
  }

  return context;
}

/**
 * Clear stored chat context
 */
export function clearChatContext(): void {
  if (!isBrowser()) {
    return;
  }

  try {
    localStorage.removeItem(CHAT_CONTEXT_STORAGE_KEY);
    console.log('[Chat Storage] Cleared chat context');
  } catch (error) {
    console.warn('[Chat Storage] Failed to clear chat context:', error);
  }
}

/**
 * Restore messages from stored context
 * Cleans __THINKING__ markers and validates progress line format
 */
export function restoreMessagesFromContext(context: StoredChatContext): ChatMessage[] {
  try {
    const restored = context.messages.map((msg) => {
      // Remove any __THINKING__ markers that might have been stored
      let cleanContent = removeThinkingMarkers(msg.content);

      // Validate and clean progress lines using utility functions
      const { mainContent, progressLines } = parseProgressLines(cleanContent);

      // Filter progress lines to keep only valid ones (starting with ○ or ●✓)
      // or lines that are part of the main content (not progress lines)
      const validProgressLines = progressLines.filter((line) => {
        const trimmed = line.trim();
        return (
          trimmed.length > 0 &&
          (trimmed.startsWith('○') || trimmed.startsWith('●✓') || !trimmed.match(/^[○●✓]/))
        );
      });

      // Reconstruct content with validated progress lines
      cleanContent = reconstructMessageContent(mainContent, validProgressLines);

      return {
        id: msg.id,
        content: cleanContent,
        sender: msg.sender,
        timestamp: new Date(msg.timestamp),
        mode: msg.mode,
        isScreenAccessRequest: msg.isScreenAccessRequest,
        isSystemMessage: msg.isSystemMessage, // Preserve system messages (mode changes, etc.)
      };
    });

    // Log system messages being restored for verification
    const systemMessages = restored.filter((msg) => msg.isSystemMessage);
    if (systemMessages.length > 0) {
      console.log('[Chat Storage] Restoring system messages:', {
        count: systemMessages.length,
        messages: systemMessages.map((m) => ({ id: m.id, content: m.content })),
      });
    }

    return restored;
  } catch (error) {
    console.warn('[Chat Storage] Failed to restore messages:', error);
    return [];
  }
}

export interface PendingToolCall {
  chat_id: string;
  requestId: string | number;
  toolName: string;
  arguments: Record<string, unknown>;
  mode: string;
  explanation: string;
  timestamp: number;
}

/**
 * Store pending tool call
 */
export function storePendingToolCall(
  chatId: string,
  requestId: string | number,
  toolName: string,
  arguments_: Record<string, unknown>,
  mode: string,
  explanation: string
): void {
  if (!isBrowser()) {
    return;
  }

  try {
    const pendingToolCall: PendingToolCall = {
      chat_id: chatId,
      requestId,
      toolName,
      arguments: arguments_,
      mode,
      explanation,
      timestamp: Date.now(),
    };

    localStorage.setItem(PENDING_TOOL_CALL_STORAGE_KEY, JSON.stringify(pendingToolCall));
    console.log('[Chat Storage] Stored pending tool call:', {
      chatId,
      requestId,
      toolName,
      mode,
    });
  } catch (error) {
    console.warn('[Chat Storage] Failed to store pending tool call:', error);
  }
}

/**
 * Get pending tool call
 */
export function getPendingToolCall(chatId: string): PendingToolCall | null {
  if (!isBrowser()) {
    return null;
  }

  try {
    const stored = localStorage.getItem(PENDING_TOOL_CALL_STORAGE_KEY);
    if (!stored) {
      return null;
    }

    const pendingToolCall: PendingToolCall = JSON.parse(stored);

    // Validate structure
    if (!pendingToolCall || typeof pendingToolCall !== 'object') {
      console.warn('[Chat Storage] Invalid pending tool call format');
      return null;
    }

    // Check if it matches current chat_id
    if (pendingToolCall.chat_id !== chatId) {
      console.log('[Chat Storage] Pending tool call chat_id mismatch, ignoring');
      return null;
    }

    // Check expiration (5 minutes)
    const age = Date.now() - pendingToolCall.timestamp;
    if (age > PENDING_TOOL_CALL_EXPIRY_MS) {
      console.log('[Chat Storage] Pending tool call expired, ignoring');
      clearPendingToolCall();
      return null;
    }

    return pendingToolCall;
  } catch (error) {
    console.warn('[Chat Storage] Failed to get pending tool call:', error);
    return null;
  }
}

/**
 * Clear pending tool call
 */
export function clearPendingToolCall(): void {
  if (!isBrowser()) {
    return;
  }

  try {
    localStorage.removeItem(PENDING_TOOL_CALL_STORAGE_KEY);
    console.log('[Chat Storage] Cleared pending tool call');
  } catch (error) {
    console.warn('[Chat Storage] Failed to clear pending tool call:', error);
  }
}
