/**
 * Chat ID Storage Utility
 *
 * Manages chat_id storage in browser localStorage.
 * The chat_id is generated by the API and stored for persistence across page refreshes.
 */

import { isBrowser } from './typeGuards';

const CHAT_ID_STORAGE_KEY = 'marketrix_chat_id';

/**
 * Get chat_id from localStorage
 */
export function getStoredChatId(): string | null {
  if (!isBrowser()) {
    return null;
  }

  try {
    const stored = localStorage.getItem(CHAT_ID_STORAGE_KEY);
    return stored || null;
  } catch (error) {
    console.warn('[Chat Storage] Failed to get chat_id from localStorage:', error);
    return null;
  }
}

/**
 * Store chat_id in localStorage
 */
export function storeChatId(chatId: string): void {
  if (!isBrowser()) {
    return;
  }

  try {
    localStorage.setItem(CHAT_ID_STORAGE_KEY, chatId);
    console.log('[Chat Storage] Stored chat_id:', chatId);
  } catch (error) {
    console.warn('[Chat Storage] Failed to store chat_id in localStorage:', error);
  }
}
