apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
  - ../../base
images:
  - name: marketrix/widget
    newName: marketrix.azurecr.io/dev/widget
    newTag: latest
patches:
  - patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: widget
      spec:
        template:
          spec:
            containers:
              - name: widget
                imagePullPolicy: Always
