name: Assign Reviewers
on:
  pull_request:
    types: [opened]
jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - name: Request review from dev team
        env:
          GH_TOKEN: ${{ secrets.INFRA_PAT }}
        run: gh pr edit ${{ github.event.pull_request.number }} --add-reviewer Marketrix-ai/dev -R ${{ github.repository }}
