name: Deploy WIDGET-PROD
on:
  release:
    types: [created]
jobs:
  build-and-deploy:
    runs-on: prod-runner
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Install dependencies
        run: npm ci
      - name: Build the project
        run: npm run build
      - name: Upload to Azure Storage
        run: |
          # Clear existing latest files and upload new ones
          az storage blob delete-batch --source widget --pattern "latest/*" --account-name marketrix --auth-mode login
          az storage blob upload-batch --destination widget/latest --source ./dist --account-name marketrix --overwrite --auth-mode login
      - name: Clean up build artifacts
        run: rm -rf ./dist
