name: Build WIDGET-PROD
on:
  release:
    types: [created]

jobs:
  prod-build:
    uses: ./.github/workflows/base.yml
    with:
      action: build
      environment: prod
      version: ${{ github.event.release.tag_name }}
    secrets: inherit
